### ISSUE TITLE
Slides 18-20

### ISSUE THREAD

**Issue by mkosunen** [FaderOrg/Fader25_board#10]
Slides 18-20:  Everything on these slides in incorrect, b/c it's all left over from the template from Woorham and Zhaokai's board.  Please think this through.  Who is going to test these boards and/or partially-stuffed boards?  Where will they be tested?  Do you need FPGA code?  Has that code been written yet?  Have you downloaded the FPGA coding tool?

**Comment by gwright83** [comment]
I have updated the test plan to cover these issues.  The FPGA code already exists, and runs on an Opal Kelly XEM6001 board.
