### ISSUE TITLE
Which SERDES to use

### ISSUE THREAD

**Issue by gwright83** [FaderOrg/Fader25_board#11]
I'm assuming that the SERDES we want to test are the ones on the east and west sides of the chip,
LINK_BM_TX_1_{P,N}, LINK_BM_RX_1_{P, N}, LINK_CM_TX_0_{P,N}, LINK_CM_RX_0_{P, N},
LINK_BM_TX_3_{P,N}, LINK_BM_RX_3_{P, N}, LINK_CM_TX_1_{P,N}, LINK_CM_RX_1_{P, N}.

What are REF_SERDES_CM0_{P,N} and REF_SERDES_CM1_{P,N}?

Do we need to make provision to supply an external voltage to VDD_LINK_CM0 and VDD_LINK_CM1?

**Comment by mkosunen** [comment]
We have implemented LINK_CM0 and LINK_CM1 whicjh are continuous mode serdeses requiring reference clock (REF_SERDES_CM0_{P,N} and REF_SERDES_CM1_{P,N}?). I added these to Altium schematic.

Also added corresponding supplies. See #2
