### ISSUE TITLE
Impedance levels of IO transmission lines

### ISSUE THREAD

**Issue by mkosunen** [FaderOrg/Fader25_board#20]
@caolen @gwright83 
@kostatro Can you confirm the impedance levels for the transmission lines on PCB?
50 ohm single ended, 100 ohm differential?

**Comment by kostatro** [comment]
Yes, this is correct.

 
 
  On Fri, Jun 5, 2020 at 16:29, Marko Kosunen<notifications@github.com> wrote:   


@caolen @gwright83
@kostatro Can you confirm the impedance levels for the transmission lines on PCB?
50 ohm single ended, 100 ohm differential?
