### ISSUE TITLE
Does the Altium database correspond to the board Sierra built?

### ISSUE THREAD

**Issue by gwright83** [FaderOrg/Fader25_board#21]
@kostatro 
@aflynn 
Does the Altium database from the BWRC reflect the final state of the board as manufacturer by Sierra, or did Sierra make changes that were not backported to the BWRC?

The question came up because it appears as if there are thru vias under the IC even in the 
 file fader2_blind_vias_pcb.PcbDoc.  My understanding is that these were plugged so that the under-chip bump attach points would be flat.

**Comment by aflynn** [comment]
I'm not sure about the file version.

What actually got fabricated was what I was trying to explain in my
previous email ... nothing was "plugged with epoxy".  That is, the Thru
(unplugged) vias in the first rev were replaced, I believe, by stacked
vias.  When you have stacked vias in the "thin copper foil process", the
L1-L2 via automatically gets *plated* ... i.e. filled with copper (not
plugged with epoxy and plated over).  In the "thin copper foil process"
required for the fine-feature etching, the dielectric between L1 and L2 is
required to be the thinness required for blind vias so that the plating
step by itself will fill the L1-L2 via with copper.

**Comment by aflynn** [comment]
You could ask Sierra if you like.  The contact is justinb@protoexpress.com.

**Comment by gwright83** [comment]
@aflynn 
Got it.  I will ask them just to be sure.

**Comment by kostatro** [comment]
The updated Altium file should reflect the changes required by Sierra. I don't have access to Altium to check it now... It's a good idea to ask Justin.

 
 
  On Fri, Jun 5, 2020 at 23:21, Gregory Wright<notifications@github.com> wrote:   


@aflynn
Got it. I will ask them just to be sure.

**Comment by aflynn** [comment]
Yes, I have no idea about Kosta's board, but on my last EagleX board,
Sierra did make a change that I approved during the time that their CAM
Shop asks questions, so my file in the repo is not exactly what they
manufactured ... so it happens...

(Their change did not change the functionality of my board, but it
streamlined their process.  The change was to change my Thru vias to a set
of stacked vias, as I mentioned in my previous email.)

**Comment by gwright83** [comment]
Picture of the identifying portion of the previous FADER board:
![FADER2 board identification](https://user-images.githubusercontent.com/3758632/84193203-0fb48c00-aa69-11ea-9807-8a9a6f112c09.jpg)

**Comment by gwright83** [comment]
Justin Blakely at Sierra Proto Express sent me a zip of the files used to make the existing board (Sierra job number 151023).  Here it is:
[job_151023.zip](https://github.com/FaderOrg/Fader25_board/files/4766174/job_151023.zip)

This should tell us the solder mask geometry.

**Comment by gwright83** [comment]
@caolen 
Hi Carl, you might want to take a look at the files from Sierra, including in the previous comment on this issue.

**Comment by caolen** [comment]
Greg, thanks.

I have also forwarded to Pekka and Joe.
Carl

**Comment by gwright83** [comment]
On today's phone call we agreed that the Gerber files provided by Sierra Proto Express show that there were changes made at Sierra that were not back-ported to the Altium database at the BWRC.  Rather than reverse engineering what was done at Sierra, I will close this issue and we can concentrate on a design that can be built by Nokia's preferred vendors.

There is anecdotal evidence that the Eagle chip, a RISC-V cpu plus specialized radar signal processor, may have had trouble with reliable connections to the circuit board.  Eagle was an identical size chip with the same ball pitch and its board was also made by Sierra.  The main difference was that Eagle had many more signal connections than FADER.  The problems with the Eagle board have never been explained; it is best that we concentrate on our own approach.
