### ISSUE TITLE
Stiffeners/FMC

### ISSUE THREAD

**Issue by mkosunen** [FaderOrg/Fader25_board#3]
@FaderOrg/a-team 

Slide 14 needs to be updated (where it says "FMC" in red, you can just say "No".  Stifferners are only needed for die-on-board where the board has an FMC connector).

**Comment by gwright83** [comment]
Noted on page 14 that board stiffeners are not required -- not FMC connector on this board.
Commit a66d93d

**Comment by mkosunen** [comment]
@gwright83 have you pushed your commits?

Checked. You have. Top project is just referring to old submodule.

**Comment by gwright83** [comment]
Hi Marko,

I believe I pushed all of my commits.  I'll check again.

I'm in the BWRC now.

Greg
