### ISSUE TITLE
Assembly sequence

### ISSUE THREAD

**Issue by mkosunen** [FaderOrg/Fader25_board#4]
@FaderOrg/a-team 
Slide 14
I know Kosta used Sierra for the board house and I just remembered who he used for SMT assembly (Jeditron ... I've never used them) and for die-attach, he used Quik-Pak.  But there was some order ... I don't remember.  I think it was Jeditorn (front or back SMT) then Quik-Pak then Jeditron (back or front).

**Comment by mkosunen** [comment]
@FaderOrg/a-team 

This is what I found from mo e-mail archives:

**Comment by gwright83** [comment]
Commit c0ba88f closed this.  I copied the information from Kosta to slide 15.
