### ISSUE TITLE
Number of boards

### ISSUE THREAD

**Issue by mkosunen** [FaderOrg/Fader25_board#6]
@FaderOrg/a-team 
Slide 14?
How many boards to you want fabbed (you'll need bare board spares for the two different assembly houses)?  How many do you want stuffed with die-attach only and/or how many do you want with all SMT parts in addition to die attach?  Please make these decisions and write in down in this file.

**Comment by gwright83** [comment]
Specified 16 boards in page 14 of test plan in commit 17dd4f1.

All boards that get die should have the rest of the SMT parts installed (also noted on p. 14)
