### ISSUE TITLE
Slide 15 information

### ISSUE THREAD

**Issue by mkosunen** [FaderOrg/Fader25_board#7]
@FaderOrg/a-team 
Slide 15 (everything in red is incorrect b/c it's left-over text from this template file as was filled in by Woorham/Zhaokai for their Intel22ADC board.  

Please update with info for your project.  You need to make decisions on how many boards you want ordered, for starters.  Write down exactly what you want to order on this slide.  Communicating with vendors takes a long time.  I am not good at ESP and we don't have a lot of time, so please tell me what you want by putting everything down in writing in this file.

**Comment by gwright83** [comment]
I am working on this now.  Marko, do you remember if FADER2 was die attach first, then SMT, or the other way around?

**Comment by aflynn** [comment]
I definitely remember it was in the middle of going to Jeditron twice ...

**Comment by gwright83** [comment]
It seems as if the FADER2 assembly procedure was SMT components -> flip die attach -> SMA (maybe other) connectors.  I will put that in the test plan.

**Comment by aflynn** [comment]
Are you saying it was frontside SMT first, or backside SMT first?

**Comment by gwright83** [comment]
I do not know if it was frontside or backside SMT first.  Marko, do you remember?

**Comment by mkosunen** [comment]
@FaderOrg/a-team For the order of assembly, see #4

**Comment by gwright83** [comment]
Updated bump pitch, diameter and material.  This closes the issue with slide 15.
