### ISSUE TITLE
Slide 16

### ISSUE THREAD

**Issue by mkosunen** [FaderOrg/Fader25_board#8]
@FaderOrg/a-team 
Slide 16 has unanswered (or answered as TBD).  Please make those decisions or you can't ask vendors for quotes.

**Comment by gwright83** [comment]
Brian is working on extracting a pad layout for us.  I will use what he provides to update slide 16.

**Comment by gwright83** [comment]
I extracted a higher resolution version of the bump diagram from the Excel spreadsheet and updated page 16 of the test plan.  Brian sent me a bump map (balls up) from the material submitted to the fab.  I will add this to the repo.
